#include"Bingo_Header.h"

void how_to_play()
{
    int ch;
	attron(COLOR_PAIR(2));
	mvwprintw(stdscr,1,55,"WELCOME TO THE WORLD OF BINGO\n");
	attroff(COLOR_PAIR(2));
	


	attron(COLOR_PAIR(4));
	printw("\nTHIS GAME INVOLVES SIMPLE RULES TO PLAY!");
	attroff(COLOR_PAIR(4));

	attron(COLOR_PAIR(6));
	printw("\n1. USE ARROW KEYS TO NAVIGATE THROUGH THE GRID");	
	printw("\n2. PRESS ENTER TO STRIKE A NUMBER. THE NUMBER ALREADY STRUCK CANNOT BE STRIKED");	
	printw("\n3. TO COMPLETE THE GAME YOU HAVE TO STRIKE 5 OF ROWS, COLUMNS OR THE TWO DIAGONALS");	
	attroff(COLOR_PAIR(6));
	
	attron(COLOR_PAIR(4));
	printw("\n\nHOW TO START A SERVER");
	attroff(COLOR_PAIR(4));

	attron(COLOR_PAIR(6));
	printw("\n1.PRESS ENTER IN THE OPTION START SERVER");
	printw("\n2.THIS STARTS A SCREEN WHICH DISPLAYS INFORMATION ABOUT THE PLAYERS JOINED AND PORT NUMBER");
	printw("\n3.THE PORT NUMBER ENABLES YOU TO CONNECT THE CLIENTS TO YOU");
	printw("\n4.YOU CAN START THE GAME ONLY WHEN THE PLAYERS JOINED ARE MORE THAN TWO");
	printw("\n5.TO START THE GAME PRESS ENTER AND YOU ARE READY TO ROCK AND ROLL! ");
	attroff(COLOR_PAIR(6));
	
	attron(COLOR_PAIR(4));
	printw("\n\nHOW TO CONNECT A SERVER");
	attroff(COLOR_PAIR(4));

	attron(COLOR_PAIR(6));
	printw("\n1.PRESS ENTER IN THE OPTION CONNECT TO THE SERVER");
	printw("\n2.THE SCREEN ASKS YOU TO ENTER THE PORT NUMBER OF THE SERVER WHICH YOU WANT TO CONNECT");
	printw("\n3.ENTER THE RIGHT PORT NUMBER AND PRESS ENTER TO JOIN THE SERVER");
	printw("\n4.THE SCREEN CHANGES TO THE GAME GRID. WAIT FOR THE SERVER TO START THE GAME");
	attroff(COLOR_PAIR(6));

	attron(COLOR_PAIR(4));
	printw("\n\nHOW TO PLAY MULTIPLAYER");
	attroff(COLOR_PAIR(4));

	attron(COLOR_PAIR(6));
	printw("\n1.YOUR CHANCE TO PLAY WILL BE DISPLAYED ON THE SCREEN(TOP OF THE BINGO GRID)");
	printw("\n2.YOU HAVE 10 SECONDS TO PLAY. IF THE TIMER RUNS OUT, YOU HAVE MISSED YOUR CHANCE, SO DON'T PANIC!");
	printw("\n3.THE CURSOR MOVES TO THE POSITION OF THE NUMBER STRIKED IN THE GRID, SO AS TO KNOW WHICH NUMBER YOUR OPPONENT STRIKED");
	attroff(COLOR_PAIR(6));



	attron(COLOR_PAIR(2));
	mvwprintw(stdscr,26,20,"ALL THE BEST FOR YOUR BINGO MATCHES!!! GO FOR THE BINGOS BUDDY!!!");
	attron(COLOR_PAIR(2));

	attron(COLOR_PAIR(4));
	mvwprintw(stdscr,30,1,"PRESS 'q' TO EXIT HOW TO PLAY");
	attroff(COLOR_PAIR(4));

	refresh();
    while((ch = getch())!='q');
    
return;
}
